/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aik.filterapi;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * Raw data required for filtering a bid request
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2022-03-08")
public class BidRequest implements org.apache.thrift.TBase<BidRequest, BidRequest._Fields>, java.io.Serializable, Cloneable, Comparable<BidRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BidRequest");

  private static final org.apache.thrift.protocol.TField BID_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("bidId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DAY_OF_WEEK_FIELD_DESC = new org.apache.thrift.protocol.TField("dayOfWeek", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField HOUR_FIELD_DESC = new org.apache.thrift.protocol.TField("hour", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REGION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("regionId", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CITY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("cityId", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField DOMAIN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("domainId", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField ADVERTISER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("advertiserId", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField BIDDING_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("biddingPrice", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField PAYING_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("payingPrice", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField USER_AGENT_FIELD_DESC = new org.apache.thrift.protocol.TField("userAgent", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField DEVICE_TYPE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("deviceTypeId", org.apache.thrift.protocol.TType.I32, (short)11);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BidRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BidRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String bidId; // required
  public int dayOfWeek; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String hour; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String regionId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String cityId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String domainId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String advertiserId; // required
  public long biddingPrice; // required
  public long payingPrice; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String userAgent; // required
  public int deviceTypeId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BID_ID((short)1, "bidId"),
    DAY_OF_WEEK((short)2, "dayOfWeek"),
    HOUR((short)3, "hour"),
    REGION_ID((short)4, "regionId"),
    CITY_ID((short)5, "cityId"),
    DOMAIN_ID((short)6, "domainId"),
    ADVERTISER_ID((short)7, "advertiserId"),
    BIDDING_PRICE((short)8, "biddingPrice"),
    PAYING_PRICE((short)9, "payingPrice"),
    USER_AGENT((short)10, "userAgent"),
    DEVICE_TYPE_ID((short)11, "deviceTypeId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BID_ID
          return BID_ID;
        case 2: // DAY_OF_WEEK
          return DAY_OF_WEEK;
        case 3: // HOUR
          return HOUR;
        case 4: // REGION_ID
          return REGION_ID;
        case 5: // CITY_ID
          return CITY_ID;
        case 6: // DOMAIN_ID
          return DOMAIN_ID;
        case 7: // ADVERTISER_ID
          return ADVERTISER_ID;
        case 8: // BIDDING_PRICE
          return BIDDING_PRICE;
        case 9: // PAYING_PRICE
          return PAYING_PRICE;
        case 10: // USER_AGENT
          return USER_AGENT;
        case 11: // DEVICE_TYPE_ID
          return DEVICE_TYPE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DAYOFWEEK_ISSET_ID = 0;
  private static final int __BIDDINGPRICE_ISSET_ID = 1;
  private static final int __PAYINGPRICE_ISSET_ID = 2;
  private static final int __DEVICETYPEID_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BID_ID, new org.apache.thrift.meta_data.FieldMetaData("bidId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DAY_OF_WEEK, new org.apache.thrift.meta_data.FieldMetaData("dayOfWeek", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HOUR, new org.apache.thrift.meta_data.FieldMetaData("hour", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REGION_ID, new org.apache.thrift.meta_data.FieldMetaData("regionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CITY_ID, new org.apache.thrift.meta_data.FieldMetaData("cityId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DOMAIN_ID, new org.apache.thrift.meta_data.FieldMetaData("domainId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ADVERTISER_ID, new org.apache.thrift.meta_data.FieldMetaData("advertiserId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BIDDING_PRICE, new org.apache.thrift.meta_data.FieldMetaData("biddingPrice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PAYING_PRICE, new org.apache.thrift.meta_data.FieldMetaData("payingPrice", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_AGENT, new org.apache.thrift.meta_data.FieldMetaData("userAgent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEVICE_TYPE_ID, new org.apache.thrift.meta_data.FieldMetaData("deviceTypeId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BidRequest.class, metaDataMap);
  }

  public BidRequest() {
  }

  public BidRequest(
    java.lang.String bidId,
    int dayOfWeek,
    java.lang.String hour,
    java.lang.String regionId,
    java.lang.String cityId,
    java.lang.String domainId,
    java.lang.String advertiserId,
    long biddingPrice,
    long payingPrice,
    java.lang.String userAgent,
    int deviceTypeId)
  {
    this();
    this.bidId = bidId;
    this.dayOfWeek = dayOfWeek;
    setDayOfWeekIsSet(true);
    this.hour = hour;
    this.regionId = regionId;
    this.cityId = cityId;
    this.domainId = domainId;
    this.advertiserId = advertiserId;
    this.biddingPrice = biddingPrice;
    setBiddingPriceIsSet(true);
    this.payingPrice = payingPrice;
    setPayingPriceIsSet(true);
    this.userAgent = userAgent;
    this.deviceTypeId = deviceTypeId;
    setDeviceTypeIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BidRequest(BidRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetBidId()) {
      this.bidId = other.bidId;
    }
    this.dayOfWeek = other.dayOfWeek;
    if (other.isSetHour()) {
      this.hour = other.hour;
    }
    if (other.isSetRegionId()) {
      this.regionId = other.regionId;
    }
    if (other.isSetCityId()) {
      this.cityId = other.cityId;
    }
    if (other.isSetDomainId()) {
      this.domainId = other.domainId;
    }
    if (other.isSetAdvertiserId()) {
      this.advertiserId = other.advertiserId;
    }
    this.biddingPrice = other.biddingPrice;
    this.payingPrice = other.payingPrice;
    if (other.isSetUserAgent()) {
      this.userAgent = other.userAgent;
    }
    this.deviceTypeId = other.deviceTypeId;
  }

  public BidRequest deepCopy() {
    return new BidRequest(this);
  }

  @Override
  public void clear() {
    this.bidId = null;
    setDayOfWeekIsSet(false);
    this.dayOfWeek = 0;
    this.hour = null;
    this.regionId = null;
    this.cityId = null;
    this.domainId = null;
    this.advertiserId = null;
    setBiddingPriceIsSet(false);
    this.biddingPrice = 0;
    setPayingPriceIsSet(false);
    this.payingPrice = 0;
    this.userAgent = null;
    setDeviceTypeIdIsSet(false);
    this.deviceTypeId = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getBidId() {
    return this.bidId;
  }

  public BidRequest setBidId(@org.apache.thrift.annotation.Nullable java.lang.String bidId) {
    this.bidId = bidId;
    return this;
  }

  public void unsetBidId() {
    this.bidId = null;
  }

  /** Returns true if field bidId is set (has been assigned a value) and false otherwise */
  public boolean isSetBidId() {
    return this.bidId != null;
  }

  public void setBidIdIsSet(boolean value) {
    if (!value) {
      this.bidId = null;
    }
  }

  public int getDayOfWeek() {
    return this.dayOfWeek;
  }

  public BidRequest setDayOfWeek(int dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
    setDayOfWeekIsSet(true);
    return this;
  }

  public void unsetDayOfWeek() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DAYOFWEEK_ISSET_ID);
  }

  /** Returns true if field dayOfWeek is set (has been assigned a value) and false otherwise */
  public boolean isSetDayOfWeek() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DAYOFWEEK_ISSET_ID);
  }

  public void setDayOfWeekIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DAYOFWEEK_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHour() {
    return this.hour;
  }

  public BidRequest setHour(@org.apache.thrift.annotation.Nullable java.lang.String hour) {
    this.hour = hour;
    return this;
  }

  public void unsetHour() {
    this.hour = null;
  }

  /** Returns true if field hour is set (has been assigned a value) and false otherwise */
  public boolean isSetHour() {
    return this.hour != null;
  }

  public void setHourIsSet(boolean value) {
    if (!value) {
      this.hour = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRegionId() {
    return this.regionId;
  }

  public BidRequest setRegionId(@org.apache.thrift.annotation.Nullable java.lang.String regionId) {
    this.regionId = regionId;
    return this;
  }

  public void unsetRegionId() {
    this.regionId = null;
  }

  /** Returns true if field regionId is set (has been assigned a value) and false otherwise */
  public boolean isSetRegionId() {
    return this.regionId != null;
  }

  public void setRegionIdIsSet(boolean value) {
    if (!value) {
      this.regionId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCityId() {
    return this.cityId;
  }

  public BidRequest setCityId(@org.apache.thrift.annotation.Nullable java.lang.String cityId) {
    this.cityId = cityId;
    return this;
  }

  public void unsetCityId() {
    this.cityId = null;
  }

  /** Returns true if field cityId is set (has been assigned a value) and false otherwise */
  public boolean isSetCityId() {
    return this.cityId != null;
  }

  public void setCityIdIsSet(boolean value) {
    if (!value) {
      this.cityId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDomainId() {
    return this.domainId;
  }

  public BidRequest setDomainId(@org.apache.thrift.annotation.Nullable java.lang.String domainId) {
    this.domainId = domainId;
    return this;
  }

  public void unsetDomainId() {
    this.domainId = null;
  }

  /** Returns true if field domainId is set (has been assigned a value) and false otherwise */
  public boolean isSetDomainId() {
    return this.domainId != null;
  }

  public void setDomainIdIsSet(boolean value) {
    if (!value) {
      this.domainId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAdvertiserId() {
    return this.advertiserId;
  }

  public BidRequest setAdvertiserId(@org.apache.thrift.annotation.Nullable java.lang.String advertiserId) {
    this.advertiserId = advertiserId;
    return this;
  }

  public void unsetAdvertiserId() {
    this.advertiserId = null;
  }

  /** Returns true if field advertiserId is set (has been assigned a value) and false otherwise */
  public boolean isSetAdvertiserId() {
    return this.advertiserId != null;
  }

  public void setAdvertiserIdIsSet(boolean value) {
    if (!value) {
      this.advertiserId = null;
    }
  }

  public long getBiddingPrice() {
    return this.biddingPrice;
  }

  public BidRequest setBiddingPrice(long biddingPrice) {
    this.biddingPrice = biddingPrice;
    setBiddingPriceIsSet(true);
    return this;
  }

  public void unsetBiddingPrice() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BIDDINGPRICE_ISSET_ID);
  }

  /** Returns true if field biddingPrice is set (has been assigned a value) and false otherwise */
  public boolean isSetBiddingPrice() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BIDDINGPRICE_ISSET_ID);
  }

  public void setBiddingPriceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BIDDINGPRICE_ISSET_ID, value);
  }

  public long getPayingPrice() {
    return this.payingPrice;
  }

  public BidRequest setPayingPrice(long payingPrice) {
    this.payingPrice = payingPrice;
    setPayingPriceIsSet(true);
    return this;
  }

  public void unsetPayingPrice() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PAYINGPRICE_ISSET_ID);
  }

  /** Returns true if field payingPrice is set (has been assigned a value) and false otherwise */
  public boolean isSetPayingPrice() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PAYINGPRICE_ISSET_ID);
  }

  public void setPayingPriceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PAYINGPRICE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserAgent() {
    return this.userAgent;
  }

  public BidRequest setUserAgent(@org.apache.thrift.annotation.Nullable java.lang.String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  public void unsetUserAgent() {
    this.userAgent = null;
  }

  /** Returns true if field userAgent is set (has been assigned a value) and false otherwise */
  public boolean isSetUserAgent() {
    return this.userAgent != null;
  }

  public void setUserAgentIsSet(boolean value) {
    if (!value) {
      this.userAgent = null;
    }
  }

  public int getDeviceTypeId() {
    return this.deviceTypeId;
  }

  public BidRequest setDeviceTypeId(int deviceTypeId) {
    this.deviceTypeId = deviceTypeId;
    setDeviceTypeIdIsSet(true);
    return this;
  }

  public void unsetDeviceTypeId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DEVICETYPEID_ISSET_ID);
  }

  /** Returns true if field deviceTypeId is set (has been assigned a value) and false otherwise */
  public boolean isSetDeviceTypeId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DEVICETYPEID_ISSET_ID);
  }

  public void setDeviceTypeIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DEVICETYPEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case BID_ID:
      if (value == null) {
        unsetBidId();
      } else {
        setBidId((java.lang.String)value);
      }
      break;

    case DAY_OF_WEEK:
      if (value == null) {
        unsetDayOfWeek();
      } else {
        setDayOfWeek((java.lang.Integer)value);
      }
      break;

    case HOUR:
      if (value == null) {
        unsetHour();
      } else {
        setHour((java.lang.String)value);
      }
      break;

    case REGION_ID:
      if (value == null) {
        unsetRegionId();
      } else {
        setRegionId((java.lang.String)value);
      }
      break;

    case CITY_ID:
      if (value == null) {
        unsetCityId();
      } else {
        setCityId((java.lang.String)value);
      }
      break;

    case DOMAIN_ID:
      if (value == null) {
        unsetDomainId();
      } else {
        setDomainId((java.lang.String)value);
      }
      break;

    case ADVERTISER_ID:
      if (value == null) {
        unsetAdvertiserId();
      } else {
        setAdvertiserId((java.lang.String)value);
      }
      break;

    case BIDDING_PRICE:
      if (value == null) {
        unsetBiddingPrice();
      } else {
        setBiddingPrice((java.lang.Long)value);
      }
      break;

    case PAYING_PRICE:
      if (value == null) {
        unsetPayingPrice();
      } else {
        setPayingPrice((java.lang.Long)value);
      }
      break;

    case USER_AGENT:
      if (value == null) {
        unsetUserAgent();
      } else {
        setUserAgent((java.lang.String)value);
      }
      break;

    case DEVICE_TYPE_ID:
      if (value == null) {
        unsetDeviceTypeId();
      } else {
        setDeviceTypeId((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case BID_ID:
      return getBidId();

    case DAY_OF_WEEK:
      return getDayOfWeek();

    case HOUR:
      return getHour();

    case REGION_ID:
      return getRegionId();

    case CITY_ID:
      return getCityId();

    case DOMAIN_ID:
      return getDomainId();

    case ADVERTISER_ID:
      return getAdvertiserId();

    case BIDDING_PRICE:
      return getBiddingPrice();

    case PAYING_PRICE:
      return getPayingPrice();

    case USER_AGENT:
      return getUserAgent();

    case DEVICE_TYPE_ID:
      return getDeviceTypeId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case BID_ID:
      return isSetBidId();
    case DAY_OF_WEEK:
      return isSetDayOfWeek();
    case HOUR:
      return isSetHour();
    case REGION_ID:
      return isSetRegionId();
    case CITY_ID:
      return isSetCityId();
    case DOMAIN_ID:
      return isSetDomainId();
    case ADVERTISER_ID:
      return isSetAdvertiserId();
    case BIDDING_PRICE:
      return isSetBiddingPrice();
    case PAYING_PRICE:
      return isSetPayingPrice();
    case USER_AGENT:
      return isSetUserAgent();
    case DEVICE_TYPE_ID:
      return isSetDeviceTypeId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof BidRequest)
      return this.equals((BidRequest)that);
    return false;
  }

  public boolean equals(BidRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_bidId = true && this.isSetBidId();
    boolean that_present_bidId = true && that.isSetBidId();
    if (this_present_bidId || that_present_bidId) {
      if (!(this_present_bidId && that_present_bidId))
        return false;
      if (!this.bidId.equals(that.bidId))
        return false;
    }

    boolean this_present_dayOfWeek = true;
    boolean that_present_dayOfWeek = true;
    if (this_present_dayOfWeek || that_present_dayOfWeek) {
      if (!(this_present_dayOfWeek && that_present_dayOfWeek))
        return false;
      if (this.dayOfWeek != that.dayOfWeek)
        return false;
    }

    boolean this_present_hour = true && this.isSetHour();
    boolean that_present_hour = true && that.isSetHour();
    if (this_present_hour || that_present_hour) {
      if (!(this_present_hour && that_present_hour))
        return false;
      if (!this.hour.equals(that.hour))
        return false;
    }

    boolean this_present_regionId = true && this.isSetRegionId();
    boolean that_present_regionId = true && that.isSetRegionId();
    if (this_present_regionId || that_present_regionId) {
      if (!(this_present_regionId && that_present_regionId))
        return false;
      if (!this.regionId.equals(that.regionId))
        return false;
    }

    boolean this_present_cityId = true && this.isSetCityId();
    boolean that_present_cityId = true && that.isSetCityId();
    if (this_present_cityId || that_present_cityId) {
      if (!(this_present_cityId && that_present_cityId))
        return false;
      if (!this.cityId.equals(that.cityId))
        return false;
    }

    boolean this_present_domainId = true && this.isSetDomainId();
    boolean that_present_domainId = true && that.isSetDomainId();
    if (this_present_domainId || that_present_domainId) {
      if (!(this_present_domainId && that_present_domainId))
        return false;
      if (!this.domainId.equals(that.domainId))
        return false;
    }

    boolean this_present_advertiserId = true && this.isSetAdvertiserId();
    boolean that_present_advertiserId = true && that.isSetAdvertiserId();
    if (this_present_advertiserId || that_present_advertiserId) {
      if (!(this_present_advertiserId && that_present_advertiserId))
        return false;
      if (!this.advertiserId.equals(that.advertiserId))
        return false;
    }

    boolean this_present_biddingPrice = true;
    boolean that_present_biddingPrice = true;
    if (this_present_biddingPrice || that_present_biddingPrice) {
      if (!(this_present_biddingPrice && that_present_biddingPrice))
        return false;
      if (this.biddingPrice != that.biddingPrice)
        return false;
    }

    boolean this_present_payingPrice = true;
    boolean that_present_payingPrice = true;
    if (this_present_payingPrice || that_present_payingPrice) {
      if (!(this_present_payingPrice && that_present_payingPrice))
        return false;
      if (this.payingPrice != that.payingPrice)
        return false;
    }

    boolean this_present_userAgent = true && this.isSetUserAgent();
    boolean that_present_userAgent = true && that.isSetUserAgent();
    if (this_present_userAgent || that_present_userAgent) {
      if (!(this_present_userAgent && that_present_userAgent))
        return false;
      if (!this.userAgent.equals(that.userAgent))
        return false;
    }

    boolean this_present_deviceTypeId = true;
    boolean that_present_deviceTypeId = true;
    if (this_present_deviceTypeId || that_present_deviceTypeId) {
      if (!(this_present_deviceTypeId && that_present_deviceTypeId))
        return false;
      if (this.deviceTypeId != that.deviceTypeId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetBidId()) ? 131071 : 524287);
    if (isSetBidId())
      hashCode = hashCode * 8191 + bidId.hashCode();

    hashCode = hashCode * 8191 + dayOfWeek;

    hashCode = hashCode * 8191 + ((isSetHour()) ? 131071 : 524287);
    if (isSetHour())
      hashCode = hashCode * 8191 + hour.hashCode();

    hashCode = hashCode * 8191 + ((isSetRegionId()) ? 131071 : 524287);
    if (isSetRegionId())
      hashCode = hashCode * 8191 + regionId.hashCode();

    hashCode = hashCode * 8191 + ((isSetCityId()) ? 131071 : 524287);
    if (isSetCityId())
      hashCode = hashCode * 8191 + cityId.hashCode();

    hashCode = hashCode * 8191 + ((isSetDomainId()) ? 131071 : 524287);
    if (isSetDomainId())
      hashCode = hashCode * 8191 + domainId.hashCode();

    hashCode = hashCode * 8191 + ((isSetAdvertiserId()) ? 131071 : 524287);
    if (isSetAdvertiserId())
      hashCode = hashCode * 8191 + advertiserId.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(biddingPrice);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(payingPrice);

    hashCode = hashCode * 8191 + ((isSetUserAgent()) ? 131071 : 524287);
    if (isSetUserAgent())
      hashCode = hashCode * 8191 + userAgent.hashCode();

    hashCode = hashCode * 8191 + deviceTypeId;

    return hashCode;
  }

  @Override
  public int compareTo(BidRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetBidId(), other.isSetBidId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBidId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bidId, other.bidId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDayOfWeek(), other.isSetDayOfWeek());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDayOfWeek()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dayOfWeek, other.dayOfWeek);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHour(), other.isSetHour());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHour()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hour, other.hour);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRegionId(), other.isSetRegionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.regionId, other.regionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCityId(), other.isSetCityId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCityId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cityId, other.cityId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDomainId(), other.isSetDomainId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDomainId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.domainId, other.domainId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAdvertiserId(), other.isSetAdvertiserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdvertiserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.advertiserId, other.advertiserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBiddingPrice(), other.isSetBiddingPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBiddingPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.biddingPrice, other.biddingPrice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPayingPrice(), other.isSetPayingPrice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPayingPrice()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.payingPrice, other.payingPrice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUserAgent(), other.isSetUserAgent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserAgent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userAgent, other.userAgent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDeviceTypeId(), other.isSetDeviceTypeId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeviceTypeId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deviceTypeId, other.deviceTypeId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BidRequest(");
    boolean first = true;

    sb.append("bidId:");
    if (this.bidId == null) {
      sb.append("null");
    } else {
      sb.append(this.bidId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dayOfWeek:");
    sb.append(this.dayOfWeek);
    first = false;
    if (!first) sb.append(", ");
    sb.append("hour:");
    if (this.hour == null) {
      sb.append("null");
    } else {
      sb.append(this.hour);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("regionId:");
    if (this.regionId == null) {
      sb.append("null");
    } else {
      sb.append(this.regionId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cityId:");
    if (this.cityId == null) {
      sb.append("null");
    } else {
      sb.append(this.cityId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("domainId:");
    if (this.domainId == null) {
      sb.append("null");
    } else {
      sb.append(this.domainId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("advertiserId:");
    if (this.advertiserId == null) {
      sb.append("null");
    } else {
      sb.append(this.advertiserId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("biddingPrice:");
    sb.append(this.biddingPrice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("payingPrice:");
    sb.append(this.payingPrice);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userAgent:");
    if (this.userAgent == null) {
      sb.append("null");
    } else {
      sb.append(this.userAgent);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("deviceTypeId:");
    sb.append(this.deviceTypeId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BidRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BidRequestStandardScheme getScheme() {
      return new BidRequestStandardScheme();
    }
  }

  private static class BidRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<BidRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BID_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bidId = iprot.readString();
              struct.setBidIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DAY_OF_WEEK
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.dayOfWeek = iprot.readI32();
              struct.setDayOfWeekIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HOUR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hour = iprot.readString();
              struct.setHourIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REGION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.regionId = iprot.readString();
              struct.setRegionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CITY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cityId = iprot.readString();
              struct.setCityIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DOMAIN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.domainId = iprot.readString();
              struct.setDomainIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ADVERTISER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.advertiserId = iprot.readString();
              struct.setAdvertiserIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // BIDDING_PRICE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.biddingPrice = iprot.readI64();
              struct.setBiddingPriceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PAYING_PRICE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.payingPrice = iprot.readI64();
              struct.setPayingPriceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // USER_AGENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userAgent = iprot.readString();
              struct.setUserAgentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // DEVICE_TYPE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.deviceTypeId = iprot.readI32();
              struct.setDeviceTypeIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BidRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.bidId != null) {
        oprot.writeFieldBegin(BID_ID_FIELD_DESC);
        oprot.writeString(struct.bidId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DAY_OF_WEEK_FIELD_DESC);
      oprot.writeI32(struct.dayOfWeek);
      oprot.writeFieldEnd();
      if (struct.hour != null) {
        oprot.writeFieldBegin(HOUR_FIELD_DESC);
        oprot.writeString(struct.hour);
        oprot.writeFieldEnd();
      }
      if (struct.regionId != null) {
        oprot.writeFieldBegin(REGION_ID_FIELD_DESC);
        oprot.writeString(struct.regionId);
        oprot.writeFieldEnd();
      }
      if (struct.cityId != null) {
        oprot.writeFieldBegin(CITY_ID_FIELD_DESC);
        oprot.writeString(struct.cityId);
        oprot.writeFieldEnd();
      }
      if (struct.domainId != null) {
        oprot.writeFieldBegin(DOMAIN_ID_FIELD_DESC);
        oprot.writeString(struct.domainId);
        oprot.writeFieldEnd();
      }
      if (struct.advertiserId != null) {
        oprot.writeFieldBegin(ADVERTISER_ID_FIELD_DESC);
        oprot.writeString(struct.advertiserId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(BIDDING_PRICE_FIELD_DESC);
      oprot.writeI64(struct.biddingPrice);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PAYING_PRICE_FIELD_DESC);
      oprot.writeI64(struct.payingPrice);
      oprot.writeFieldEnd();
      if (struct.userAgent != null) {
        oprot.writeFieldBegin(USER_AGENT_FIELD_DESC);
        oprot.writeString(struct.userAgent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DEVICE_TYPE_ID_FIELD_DESC);
      oprot.writeI32(struct.deviceTypeId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BidRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BidRequestTupleScheme getScheme() {
      return new BidRequestTupleScheme();
    }
  }

  private static class BidRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<BidRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBidId()) {
        optionals.set(0);
      }
      if (struct.isSetDayOfWeek()) {
        optionals.set(1);
      }
      if (struct.isSetHour()) {
        optionals.set(2);
      }
      if (struct.isSetRegionId()) {
        optionals.set(3);
      }
      if (struct.isSetCityId()) {
        optionals.set(4);
      }
      if (struct.isSetDomainId()) {
        optionals.set(5);
      }
      if (struct.isSetAdvertiserId()) {
        optionals.set(6);
      }
      if (struct.isSetBiddingPrice()) {
        optionals.set(7);
      }
      if (struct.isSetPayingPrice()) {
        optionals.set(8);
      }
      if (struct.isSetUserAgent()) {
        optionals.set(9);
      }
      if (struct.isSetDeviceTypeId()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetBidId()) {
        oprot.writeString(struct.bidId);
      }
      if (struct.isSetDayOfWeek()) {
        oprot.writeI32(struct.dayOfWeek);
      }
      if (struct.isSetHour()) {
        oprot.writeString(struct.hour);
      }
      if (struct.isSetRegionId()) {
        oprot.writeString(struct.regionId);
      }
      if (struct.isSetCityId()) {
        oprot.writeString(struct.cityId);
      }
      if (struct.isSetDomainId()) {
        oprot.writeString(struct.domainId);
      }
      if (struct.isSetAdvertiserId()) {
        oprot.writeString(struct.advertiserId);
      }
      if (struct.isSetBiddingPrice()) {
        oprot.writeI64(struct.biddingPrice);
      }
      if (struct.isSetPayingPrice()) {
        oprot.writeI64(struct.payingPrice);
      }
      if (struct.isSetUserAgent()) {
        oprot.writeString(struct.userAgent);
      }
      if (struct.isSetDeviceTypeId()) {
        oprot.writeI32(struct.deviceTypeId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BidRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.bidId = iprot.readString();
        struct.setBidIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.dayOfWeek = iprot.readI32();
        struct.setDayOfWeekIsSet(true);
      }
      if (incoming.get(2)) {
        struct.hour = iprot.readString();
        struct.setHourIsSet(true);
      }
      if (incoming.get(3)) {
        struct.regionId = iprot.readString();
        struct.setRegionIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.cityId = iprot.readString();
        struct.setCityIdIsSet(true);
      }
      if (incoming.get(5)) {
        struct.domainId = iprot.readString();
        struct.setDomainIdIsSet(true);
      }
      if (incoming.get(6)) {
        struct.advertiserId = iprot.readString();
        struct.setAdvertiserIdIsSet(true);
      }
      if (incoming.get(7)) {
        struct.biddingPrice = iprot.readI64();
        struct.setBiddingPriceIsSet(true);
      }
      if (incoming.get(8)) {
        struct.payingPrice = iprot.readI64();
        struct.setPayingPriceIsSet(true);
      }
      if (incoming.get(9)) {
        struct.userAgent = iprot.readString();
        struct.setUserAgentIsSet(true);
      }
      if (incoming.get(10)) {
        struct.deviceTypeId = iprot.readI32();
        struct.setDeviceTypeIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

